parameters:
#    rocket_project.example.class: Rocket\ProjectBundle\Example

services:
#    rocket_project.example:
#        class: %rocket_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
